routes:
  /subscribe/: members/signup
  /signin/: members/signin
  /account/: members/account
  /newsletter/: /tag/newsletter/

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
